[versions]
java = "25"
springBoot = "4.0.0"
springDependencyManagement = "1.1.7"
junit = "6.1.0-M1"
lombok = "1.18.42"
poi = "5.5.1"
springAI = "2.0.0-M1"


[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-ai-starter = { module = "org.springframework.ai:spring-ai-starter", version.ref = "springAI" }
apache-poi = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
